### PR TITLE
Indentation clean up & removed invalid css

### PR DESCRIPTION
**Pull request by apathy-dude**
No changes are made to rendering or code here.  Just standardizing indentation using an auto formatter and removing css that's completely useless.

The main reason for doing this is so that the diff that I do commit with actual changes will not be hidden inside indentation changes.

### CODE REVIEW

**Comment by clevett** [comment]
The indents were intentional as it makes it easier for me to hide things in Sublime and visualize how changes flow. I don't mind loosing them to make it easier for another person to read. :)

**Comment by apathy-dude** [comment]
Would you mind having a sass compilation step to create the css file?  That way you can keep your indents and it'll look considerably better.

**Comment by clevett** [comment]
I don't mind loosing the indents. Though this repo was out of sync with the official Roll20 one. I'm trying to fix all the merge conflicts now. I might need to revert, sync everything, then add this again...Git is not my friends this week. :)

**Comment by apathy-dude** [comment]
This isn't a complaint, just want to figure out how we're going to handle it.  The latest pushes to the repository removed many of the formatting changes I put in adding in the extra tabs and spaces.

To keep things organized I recommend we add scss/sass which will compile into css so we can keep the tabs since it's part of the language and there is really no learning curve between css to scss other than we'll have to add something like nodejs grunt or gulp files which I can setup pretty quickly.

The main feature of scss I'm talking about is [nesting](https://sass-lang.com/guide#topic-3) which will make formatting easier.  You said you use sublime which has [sass/scss support](http://sublimetexttips.com/how-to-add-sass-support-in-sublime-text/).  I've never heard of visialize so I don't know if it's supported.

If you don't want to add a compilation step to the build I fully understand and I'll try and understand the indentation style you're using and follow it.

**Pull request merged**
